name: StorytimeApp

options:
  minimumXcodeGenVersion: 2.40.0
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "16.0"

configs:
  Debug: debug
  Release: release

targets:
  StorytimeApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: StorytimeApp
        excludes:
          - "**/*.plist"
    settings:
      base:
        PRODUCT_NAME: StorytimeApp
        PRODUCT_BUNDLE_IDENTIFIER: com.storytime.app
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: StorytimeApp/Info.plist
        SWIFT_VERSION: "5.10"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    scheme:
      gatherCoverageData: false
      testTargets: []
